-- Eliminar tablas si existen (opcional, útil para desarrollo)
DROP TABLE IF EXISTS prestamo CASCADE;
DROP TABLE IF EXISTS libro CASCADE;
DROP TABLE IF EXISTS musica CASCADE;
DROP TABLE IF EXISTS pelicula CASCADE;
DROP TABLE IF EXISTS tipo_item_formato CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS formato CASCADE;
DROP TABLE IF EXISTS tipo_item CASCADE;
DROP TABLE IF EXISTS persona CASCADE;


-- Tabla TipoItem
CREATE TABLE tipo_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL
);

-- Tabla Formato
CREATE TABLE formato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL
);

-- Tabla de unión TipoItemFormato (Relación muchos a muchos)
CREATE TABLE tipo_item_formato (
    tipo_item_id BIGINT NOT NULL,
    formato_id BIGINT NOT NULL,
    PRIMARY KEY (tipo_item_id, formato_id),
    FOREIGN KEY (tipo_item_id) REFERENCES tipo_item(id),
    FOREIGN KEY (formato_id) REFERENCES formato(id)
);

-- Tabla Item
CREATE TABLE item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    tipo_id BIGINT,
    formato_id BIGINT,
    ubicacion VARCHAR(100),
    fecha DATE,
    estado VARCHAR(20) DEFAULT 'DISPONIBLE', -- Mapea el Enum EstadoItem
    FOREIGN KEY (tipo_id) REFERENCES tipo_item(id),
    FOREIGN KEY (formato_id) REFERENCES formato(id)
);

-- Tabla Libro (Relación uno a uno con Item)
CREATE TABLE libro (
    item_id BIGINT PRIMARY KEY,
    autor VARCHAR(30),
    isbn VARCHAR(255),
    editorial VARCHAR(30),
    numero_paginas INT CHECK (numero_paginas > 0),
    fecha_publicacion DATE,
    FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE
);

-- Tabla Musica (Relación uno a uno con Item)
CREATE TABLE musica (
    item_id BIGINT PRIMARY KEY,
    genero VARCHAR(20),
    cantante VARCHAR(30),
    album VARCHAR(30),
    duracion VARCHAR(255), -- O podrías usar INT para segundos si prefieres
    FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE
);

-- Tabla Pelicula (Relación uno a uno con Item)
CREATE TABLE pelicula (
    item_id BIGINT PRIMARY KEY,
    director VARCHAR(40),
    duracion INT CHECK (duracion > 0), -- Duración en minutos
    genero VARCHAR(30),
    fecha_estreno DATE,
    FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE
);

-- Tabla Persona
CREATE TABLE persona (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    direccion VARCHAR(100),
    email VARCHAR(255) NOT NULL,
    telefono VARCHAR(255)
);

-- Tabla Prestamo
CREATE TABLE prestamo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    persona_id BIGINT NOT NULL,
    fecha_prestamo DATE,
    fecha_devolucion DATE,
    fecha_prevista_devolucion DATE,
    borrado BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (persona_id) REFERENCES persona(id)
);

